# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1494212572);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1494212692);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1494212332);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1494212452);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1494212211);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1494212812);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 34);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1494225872013");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1494227638013");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1494225875241");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1494229475241");
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160209234718");
user_pref("browser.slowStartup.averageTime", 42710);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20160209234718");
user_pref("browser.startup.homepage_override.mstone", "44.0.2");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.urlbar.suggest.searches", true);
user_pref("browser.urlbar.userMadeSearchSuggestionsChoice", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1492758704879");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1492749857750");
user_pref("datareporting.policy.firstRunTime", "1492672304877");
user_pref("datareporting.sessions.current.activeTicks", 0);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 55223);
user_pref("datareporting.sessions.current.main", 3472);
user_pref("datareporting.sessions.current.sessionRestored", 62583);
user_pref("datareporting.sessions.current.startTime", "1494225791822");
user_pref("datareporting.sessions.current.totalTime", 120);
user_pref("datareporting.sessions.currentIndex", 27);
user_pref("datareporting.sessions.previous.20", "{\"s\":1493880633002,\"a\":4,\"t\":125,\"c\":false,\"m\":5166,\"fp\":107613,\"sr\":-1}");
user_pref("datareporting.sessions.previous.21", "{\"s\":1493881361734,\"a\":21,\"t\":146,\"c\":true,\"m\":1317,\"fp\":20137,\"sr\":29928}");
user_pref("datareporting.sessions.previous.22", "{\"s\":1493882555464,\"a\":5,\"t\":61,\"c\":false,\"m\":2500,\"fp\":24707,\"sr\":30329}");
user_pref("datareporting.sessions.previous.23", "{\"s\":1493890064718,\"a\":107,\"t\":4995,\"c\":true,\"m\":3728,\"fp\":28714,\"sr\":46872}");
user_pref("datareporting.sessions.previous.24", "{\"s\":1493955899042,\"a\":17,\"t\":6624,\"c\":false,\"m\":6497,\"fp\":52180,\"sr\":89312}");
user_pref("datareporting.sessions.previous.25", "{\"s\":1494057487648,\"a\":3,\"t\":2675,\"c\":true,\"m\":3918,\"fp\":57426,\"sr\":65189}");
user_pref("datareporting.sessions.previous.26", "{\"s\":1494212080130,\"a\":3,\"t\":259,\"c\":false,\"m\":3073,\"fp\":24067,\"sr\":27971}");
user_pref("datareporting.sessions.prunedIndex", 19);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 8);
user_pref("extensions.blocklist.pingCountVersion", 8);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:44.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1494212574);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20170302.01");
user_pref("extensions.lastAppVersion", "44.0.2");
user_pref("extensions.lastPlatformVersion", "44.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"52.0.2\",\"st\":1490804278000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"52.0.2\",\"st\":1490804278000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455750937000,\"mt\":1455063905000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":false,\"v\":\"3.2\",\"st\":1442597111000}}}");
user_pref("gecko.buildID", "20160209234718");
user_pref("gecko.mstone", "44.0.2");
user_pref("idle.lastDailyNotification", 1494213309);
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1492749913);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20160209234718");
user_pref("media.gmp-manager.lastCheck", 1494212164);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1494059942);
user_pref("places.history.expiration.transient_current_max_pages", 26221);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1492935682);
user_pref("toolkit.startup.last_success", 1494225795);
user_pref("toolkit.telemetry.cachedClientID", "f1466d27-8182-41dc-b1a2-a29d5f878ec4");
user_pref("toolkit.telemetry.previousBuildID", "20160209234718");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
